# Generated by Django 2.0.4 on 2018-05-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.CharField(choices=[('abc1', 'ABC1'), ('abc2', 'ABC2'), ('abc3', 'ABC3')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='sm',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='dm.Dummy'),
        ),
    ]
